
		align	4
		label	L825_len__hla_ word
		dd	010h
		dd	010h
		label	L825_str__hla_ byte
		db	"Gimme a number: "
		db	0

		db	0
		db	0
		db	0

		align	4
		label	L896_len__hla_ word
		dd	08h
		dd	08h
		label	L896_str__hla_ byte
		db	"crazy 8!"
		db	0

		db	0
		db	0
		db	0

		align	4
		label	L914_len__hla_ word
		dd	09h
		dd	09h
		label	L914_str__hla_ byte
		db	"regular 8"
		db	0

		db	0
		db	0

		align	4
		label	L932_len__hla_ word
		dd	0ah
		dd	0ah
		label	L932_str__hla_ byte
		db	"Game Over!"
		db	0

		db	0

		align	4
		label	L941_len__hla_ word
		dd	08h
		dd	08h
		label	L941_str__hla_ byte
		db	"Score = "
		db	0

		db	0
		db	0
		db	0

		align	4
		label	L965_len__hla_ word
		dd	010h
		dd	010h
		label	L965_str__hla_ byte
		db	"Program Finished"
		db	0

		db	0
		db	0
		db	0
