		global2	__imp__MessageBoxA@16,dword
		global2	__imp__ExitProcess@4,dword

		section	'.text' code readable executable align 16
		global	STDOUT_PUTI32
		global	STDOUT_NEWLN
		global	DefaultExceptionHandler__hla_
		global	abstract__hla_
		global	HardwareException__hla_
		global	BuildExcepts__hla_
		global	STDOUT_PUTS
		global	STDIN_GETI32
		global	Raise__hla_
		global	shortDfltExcept__hla_

		public	MainPgmCoroutine__hla_
		public	DfltExHndlr__hla_
		public	_HLAMain
		public	HWexcept__hla_
L1234_str__hla_ equ	L846_str__hla_	;
L1220_str__hla_ equ	L846_str__hla_	;
L1206_str__hla_ equ	L846_str__hla_	;
L1192_str__hla_ equ	L846_str__hla_	;
L1178_str__hla_ equ	L846_str__hla_	;
L1151_str__hla_ equ	L846_str__hla_	;
L1137_str__hla_ equ	L846_str__hla_	;
L1123_str__hla_ equ	L846_str__hla_	;
L1109_str__hla_ equ	L846_str__hla_	;
L1095_str__hla_ equ	L846_str__hla_	;
L1068_str__hla_ equ	L846_str__hla_	;
L1054_str__hla_ equ	L846_str__hla_	;
L1040_str__hla_ equ	L846_str__hla_	;
L1026_str__hla_ equ	L846_str__hla_	;
L1012_str__hla_ equ	L846_str__hla_	;
L985_str__hla_  equ	L846_str__hla_	;
L971_str__hla_  equ	L846_str__hla_	;
L957_str__hla_  equ	L846_str__hla_	;
L943_str__hla_  equ	L846_str__hla_	;
L929_str__hla_  equ	L846_str__hla_	;
L902_str__hla_  equ	L846_str__hla_	;
L888_str__hla_  equ	L846_str__hla_	;
L874_str__hla_  equ	L846_str__hla_	;
L860_str__hla_  equ	L846_str__hla_	;
