
		align	4
		label	L823_len__hla_ word
		dd	017h
		dd	017h
		label	L823_str__hla_ byte
		db	"What's in your wallet: "
		db	0


		align	4
		label	L845_len__hla_ word
		dd	08h
		dd	08h
		label	L845_str__hla_ byte
		db	"This is "
		db	0

		db	0
		db	0
		db	0

		align	4
		label	L859_len__hla_ word
		dd	012h
		dd	012h
		label	L859_str__hla_ byte
		db	" in British pounds"
		db	0

		db	0

		align	4
		label	L891_len__hla_ word
		dd	011h
		dd	011h
		label	L891_str__hla_ byte
		db	" in Mexican pesos"
		db	0

		db	0
		db	0

		align	4
		label	L909_len__hla_ word
		dd	014h
		dd	014h
		label	L909_str__hla_ byte
		db	"What's your number: "
		db	0

		db	0
		db	0
		db	0
