		global2	__imp__MessageBoxA@16,dword
		global2	__imp__ExitProcess@4,dword

		section	'.text' code readable executable align 16
		global	STDOUT_PUTR32
		global	STDOUT_NEWLN
		global	DefaultExceptionHandler__hla_
		global	abstract__hla_
		global	HardwareException__hla_
		global	STDIN_GETF
		global	BuildExcepts__hla_
		global	STDOUT_PUTS
		global	Raise__hla_
		global	shortDfltExcept__hla_

		public	MainPgmCoroutine__hla_
		public	DfltExHndlr__hla_
		public	_HLAMain
		public	HWexcept__hla_
L977_str__hla_  equ	L891_str__hla_	;
L963_str__hla_  equ	L845_str__hla_	;
L945_str__hla_  equ	L859_str__hla_	;
L931_str__hla_  equ	L845_str__hla_	;
L877_str__hla_  equ	L845_str__hla_	;
