
		align	4
		label	L837_len__hla_ word
		dd	011h
		dd	011h
		label	L837_str__hla_ byte
		db	"put number here: "
		db	0

		db	0
		db	0

		align	4
		label	L925_len__hla_ word
		dd	09h
		dd	09h
		label	L925_str__hla_ byte
		db	"largest( "
		db	0

		db	0
		db	0

		align	4
		label	L954_len__hla_ word
		dd	02h
		dd	02h
		label	L954_str__hla_ byte
		db	", "
		db	0

		db	0

		align	4
		label	L1041_len__hla_ word
		dd	0ah
		dd	0ah
		label	L1041_str__hla_ byte
		db	" ) equals "
		db	0

		db	0

		align	4
		label	L1055_len__hla_ word
		dd	01h
		dd	01h
		label	L1055_str__hla_ byte
		db	"!"
		db	0

		db	0
		db	0
