		global2	__imp__MessageBoxA@16,dword
		global2	__imp__ExitProcess@4,dword

		section	'.text' code readable executable align 16
		global	STDIN_GETI8
		global	STDOUT_NEWLN
		global	DefaultExceptionHandler__hla_
		global	abstract__hla_
		global	STDOUT_PUTI8
		global	HardwareException__hla_
		global	BuildExcepts__hla_
		global	STDOUT_PUTS
		global	Raise__hla_
		global	shortDfltExcept__hla_

		public	MainPgmCoroutine__hla_
		public	DfltExHndlr__hla_
		public	_HLAMain
		public	HWexcept__hla_
L1012_str__hla_ equ	L954_str__hla_	;
L983_str__hla_  equ	L954_str__hla_	;
L903_str__hla_  equ	L837_str__hla_	;
L881_str__hla_  equ	L837_str__hla_	;
L859_str__hla_  equ	L837_str__hla_	;
