		global2	__imp__MessageBoxA@16,dword
		global2	__imp__ExitProcess@4,dword

		section	'.text' code readable executable align 16
		global	STDOUT_PUTI32
		global	STDOUT_NEWLN
		global	DefaultExceptionHandler__hla_
		global	abstract__hla_
		global	HardwareException__hla_
		global	BuildExcepts__hla_
		global	STDOUT_PUTS
		global	STDIN_GETI32
		global	Raise__hla_
		global	shortDfltExcept__hla_

		public	MainPgmCoroutine__hla_
		public	DfltExHndlr__hla_
		public	_HLAMain
		public	HWexcept__hla_
L1071_str__hla_ equ	L958_str__hla_	;
L1060_str__hla_ equ	L947_str__hla_	;
L1040_str__hla_ equ	L984_str__hla_	;
L1029_str__hla_ equ	L916_str__hla_	;
L1015_str__hla_ equ	L958_str__hla_	;
L1004_str__hla_ equ	L947_str__hla_	;
L973_str__hla_  equ	L916_str__hla_	;
L893_str__hla_  equ	L823_str__hla_	;
L869_str__hla_  equ	L823_str__hla_	;
L845_str__hla_  equ	L823_str__hla_	;
