
		align	4
		label	L823_len__hla_ word
		dd	0ch
		dd	0ch
		label	L823_str__hla_ byte
		db	"Gimme data: "
		db	0

		db	0
		db	0
		db	0

		align	4
		label	L916_len__hla_ word
		dd	019h
		dd	019h
		label	L916_str__hla_ byte
		db	"Data entry ended because "
		db	0

		db	0
		db	0

		align	4
		label	L927_len__hla_ word
		dd	014h
		dd	014h
		label	L927_str__hla_ byte
		db	" is not bigger than "
		db	0

		db	0
		db	0
		db	0

		align	4
		label	L947_len__hla_ word
		dd	0bh
		dd	0bh
		label	L947_str__hla_ byte
		db	"There were "
		db	0


		align	4
		label	L958_len__hla_ word
		dd	01dh
		dd	01dh
		label	L958_str__hla_ byte
		db	" numbers entered successfully"
		db	0

		db	0
		db	0

		align	4
		label	L984_len__hla_ word
		dd	015h
		dd	015h
		label	L984_str__hla_ byte
		db	" is not smaller than "
		db	0

		db	0
		db	0
