
		align	4
		label	L828_len__hla_ word
		dd	0bh
		dd	0bh
		label	L828_str__hla_ byte
		db	"Feed Me i: "
		db	0


		align	4
		label	L850_len__hla_ word
		dd	0bh
		dd	0bh
		label	L850_str__hla_ byte
		db	"Feed Me j: "
		db	0


		align	4
		label	L872_len__hla_ word
		dd	0bh
		dd	0bh
		label	L872_str__hla_ byte
		db	"Feed Me k: "
		db	0


		align	4
		label	L894_len__hla_ word
		dd	06h
		dd	06h
		label	L894_str__hla_ byte
		db	"EAX = "
		db	0

		db	0
