
		align	4
		label	L851_len__hla_ word
		dd	020h
		dd	020h
		label	L851_str__hla_ byte
		db	"Please enter a string to process"
		db	0

		db	0
		db	0
		db	0

		align	4
		label	L869_len__hla_ word
		dd	026h
		dd	026h
		label	L869_str__hla_ byte
		db	"----> here is the string you entered: "
		db	0

		db	0

		align	4
		label	L883_len__hla_ word
		dd	01eh
		dd	01eh
		label	L883_str__hla_ byte
		db	"after has1sand0s --- result = "
		db	0

		db	0
