
		align	4
		label	L833_len__hla_ word
		dd	09h
		dd	09h
		label	L833_str__hla_ byte
		db	"Gimme X: "
		db	0

		db	0
		db	0

		align	4
		label	L855_len__hla_ word
		dd	09h
		dd	09h
		label	L855_str__hla_ byte
		db	"Gimme Y: "
		db	0

		db	0
		db	0

		align	4
		label	L877_len__hla_ word
		dd	09h
		dd	09h
		label	L877_str__hla_ byte
		db	"Gimme Z: "
		db	0

		db	0
		db	0

		align	4
		label	L899_len__hla_ word
		dd	013h
		dd	013h
		label	L899_str__hla_ byte
		db	"After sorting, X = "
		db	0


		align	4
		label	L913_len__hla_ word
		dd	06h
		dd	06h
		label	L913_str__hla_ byte
		db	", Y = "
		db	0

		db	0

		align	4
		label	L927_len__hla_ word
		dd	06h
		dd	06h
		label	L927_str__hla_ byte
		db	", Z = "
		db	0

		db	0
