
		align	4
		label	L849_len__hla_ word
		dd	020h
		dd	020h
		label	L849_str__hla_ byte
		db	"Please enter a string to process"
		db	0

		db	0
		db	0
		db	0

		align	4
		label	L867_len__hla_ word
		dd	026h
		dd	026h
		label	L867_str__hla_ byte
		db	"----> here is the string you entered: "
		db	0

		db	0

		align	4
		label	L881_len__hla_ word
		dd	01ah
		dd	01ah
		label	L881_str__hla_ byte
		db	"after hasTwozs --- result="
		db	0

		db	0
