
		align	4
		label	L820_len__hla_ word
		dd	02eh
		dd	02eh
		label	L820_str__hla_ byte
		db	"Feed me(4 hex digits ending with srttccbbmm): "
		db	0

		db	0

		align	4
		label	L845_len__hla_ word
		dd	0ah
		dd	0ah
		label	L845_str__hla_ byte
		db	"No sunroof"
		db	0

		db	0

		align	4
		label	L860_len__hla_ word
		dd	07h
		dd	07h
		label	L860_str__hla_ byte
		db	"Sunroof"
		db	0


		align	4
		label	L877_len__hla_ word
		dd	0bh
		dd	0bh
		label	L877_str__hla_ byte
		db	"No roofrack"
		db	0


		align	4
		label	L892_len__hla_ word
		dd	08h
		dd	08h
		label	L892_str__hla_ byte
		db	"Roofrack"
		db	0

		db	0
		db	0
		db	0

		align	4
		label	L911_len__hla_ word
		dd	07h
		dd	07h
		label	L911_str__hla_ byte
		db	"18 inch"
		db	0


		align	4
		label	L926_len__hla_ word
		dd	07h
		dd	07h
		label	L926_str__hla_ byte
		db	"19 inch"
		db	0


		align	4
		label	L940_len__hla_ word
		dd	07h
		dd	07h
		label	L940_str__hla_ byte
		db	"20 inch"
		db	0


		align	4
		label	L954_len__hla_ word
		dd	07h
		dd	07h
		label	L954_str__hla_ byte
		db	"21 inch"
		db	0


		align	4
		label	L968_len__hla_ word
		dd	01h
		dd	01h
		label	L968_str__hla_ byte
		db	" "
		db	0

		db	0
		db	0

		align	4
		label	L987_len__hla_ word
		dd	04h
		dd	04h
		label	L987_str__hla_ byte
		db	"Blue"
		db	0

		db	0
		db	0
		db	0

		align	4
		label	L1002_len__hla_ word
		dd	03h
		dd	03h
		label	L1002_str__hla_ byte
		db	"Red"
		db	0


		align	4
		label	L1016_len__hla_ word
		dd	05h
		dd	05h
		label	L1016_str__hla_ byte
		db	"White"
		db	0

		db	0
		db	0

		align	4
		label	L1030_len__hla_ word
		dd	05h
		dd	05h
		label	L1030_str__hla_ byte
		db	"Black"
		db	0

		db	0
		db	0

		align	4
		label	L1063_len__hla_ word
		dd	06h
		dd	06h
		label	L1063_str__hla_ byte
		db	"60 kwH"
		db	0

		db	0

		align	4
		label	L1078_len__hla_ word
		dd	06h
		dd	06h
		label	L1078_str__hla_ byte
		db	"75 kwH"
		db	0

		db	0

		align	4
		label	L1092_len__hla_ word
		dd	06h
		dd	06h
		label	L1092_str__hla_ byte
		db	"85 kwH"
		db	0

		db	0

		align	4
		label	L1106_len__hla_ word
		dd	07h
		dd	07h
		label	L1106_str__hla_ byte
		db	"100 kwH"
		db	0


		align	4
		label	L1139_len__hla_ word
		dd	07h
		dd	07h
		label	L1139_str__hla_ byte
		db	"Model S"
		db	0


		align	4
		label	L1154_len__hla_ word
		dd	07h
		dd	07h
		label	L1154_str__hla_ byte
		db	"Model X"
		db	0


		align	4
		label	L1168_len__hla_ word
		dd	07h
		dd	07h
		label	L1168_str__hla_ byte
		db	"Model 3"
		db	0


		align	4
		label	L1182_len__hla_ word
		dd	07h
		dd	07h
		label	L1182_str__hla_ byte
		db	"Model Y"
		db	0

