		global2	__imp__MessageBoxA@16,dword
		global2	__imp__ExitProcess@4,dword

		section	'.text' code readable executable align 16
		global	STDIN_GETI8
		global	STDOUT_NEWLN
		global	DefaultExceptionHandler__hla_
		global	abstract__hla_
		global	STDOUT_PUTI8
		global	HardwareException__hla_
		global	BuildExcepts__hla_
		global	STDOUT_PUTS
		global	Raise__hla_
		global	shortDfltExcept__hla_

		public	MainPgmCoroutine__hla_
		public	DfltExHndlr__hla_
		public	_HLAMain
		public	HWexcept__hla_
L1143_str__hla_ equ	L886_str__hla_	;
L1123_str__hla_ equ	L886_str__hla_	;
L1103_str__hla_ equ	L866_str__hla_	;
L1064_str__hla_ equ	L886_str__hla_	;
L1044_str__hla_ equ	L886_str__hla_	;
L1024_str__hla_ equ	L866_str__hla_	;
L985_str__hla_  equ	L886_str__hla_	;
L965_str__hla_  equ	L886_str__hla_	;
L945_str__hla_  equ	L866_str__hla_	;
L906_str__hla_  equ	L886_str__hla_	;
