
		align	4
		label	L820_len__hla_ word
		dd	018h
		dd	018h
		label	L820_str__hla_ byte
		db	"Gimme a starting vlaue: "
		db	0

		db	0
		db	0
		db	0

		align	4
		label	L842_len__hla_ word
		dd	0ch
		dd	0ch
		label	L842_str__hla_ byte
		db	"Double Table"
		db	0

		db	0
		db	0
		db	0

		align	4
		label	L866_len__hla_ word
		dd	02h
		dd	02h
		label	L866_str__hla_ byte
		db	": "
		db	0

		db	0

		align	4
		label	L886_len__hla_ word
		dd	01h
		dd	01h
		label	L886_str__hla_ byte
		db	" "
		db	0

		db	0
		db	0
