		global2	__imp__MessageBoxA@16,dword
		global2	__imp__ExitProcess@4,dword

		section	'.text' code readable executable align 16
		global	STR_FREE
		global	STDIN_FLUSHINPUT
		global	STDOUT_NEWLN
		global	DefaultExceptionHandler__hla_
		global	abstract__hla_
		global	STDOUT_PUTI8
		global	HardwareException__hla_
		global	BuildExcepts__hla_
		global	STDOUT_PUTS
		global	STDOUT_PUTC
		global	Raise__hla_
		global	STDIN_A_GETS
		global	shortDfltExcept__hla_

		public	MainPgmCoroutine__hla_
		public	DfltExHndlr__hla_
		public	_HLAMain
		public	HWexcept__hla_
L847_stringData__hla_ equ	L823_stringData__hla_
L848_stringData__hla_ equ	L823_stringData__hla_
L863_stringData__hla_ equ	L823_stringData__hla_
