
		align	4
		label	L832_len__hla_ word
		dd	015h
		dd	015h
		label	L832_str__hla_ byte
		db	"Gimme a value for a: "
		db	0

		db	0
		db	0

		align	4
		label	L854_len__hla_ word
		dd	015h
		dd	015h
		label	L854_str__hla_ byte
		db	"Gimme a value for b: "
		db	0

		db	0
		db	0

		align	4
		label	L876_len__hla_ word
		dd	015h
		dd	015h
		label	L876_str__hla_ byte
		db	"Gimme a value for c: "
		db	0

		db	0
		db	0
		label	L885_fpconst__hla_ tword
		dt	-1.00000000000000000e+0000
		label	L886_fpconst__hla_ tword
		dt	 4.00000000000000000e+0000
		label	L887_fpconst__hla_ tword
		dt	 2.00000000000000000e+0000

		align	4
		label	L901_len__hla_ word
		dd	016h
		dd	016h
		label	L901_str__hla_ byte
		db	"The solutions are x = "
		db	0

		db	0

		align	4
		label	L915_len__hla_ word
		dd	09h
		dd	09h
		label	L915_str__hla_ byte
		db	" and x = "
		db	0

		db	0
		db	0
