
		align	4
		label	L819_len__hla_ word
		dd	02ch
		dd	02ch
		label	L819_str__hla_ byte
		db	" OOOO   CCCC TTTTT  OOOO  BBBB  EEEE RRRR   "
		db	0

		db	0
		db	0
		db	0

		align	4
		label	L837_len__hla_ word
		dd	02ch
		dd	02ch
		label	L837_str__hla_ byte
		db	"O    O C       T   O    O B   B E    R   R  "
		db	0

		db	0
		db	0
		db	0

		align	4
		label	L855_len__hla_ word
		dd	02ch
		dd	02ch
		label	L855_str__hla_ byte
		db	"O    O C       T   O    O BBBB  EEEE RRRR   "
		db	0

		db	0
		db	0
		db	0

		align	4
		label	L891_len__hla_ word
		dd	02ch
		dd	02ch
		label	L891_str__hla_ byte
		db	" OOOO   CCCC   T    OOOO  BBBB  EEEE R    R "
		db	0

		db	0
		db	0
		db	0
