
		align	4
		label	L827_len__hla_ word
		dd	0bh
		dd	0bh
		label	L827_str__hla_ byte
		db	"Feed Me i: "
		db	0


		align	4
		label	L849_len__hla_ word
		dd	0bh
		dd	0bh
		label	L849_str__hla_ byte
		db	"Feed Me j: "
		db	0


		align	4
		label	L871_len__hla_ word
		dd	0bh
		dd	0bh
		label	L871_str__hla_ byte
		db	"Feed Me k: "
		db	0


		align	4
		label	L893_len__hla_ word
		dd	05h
		dd	05h
		label	L893_str__hla_ byte
		db	"AL = "
		db	0

		db	0
		db	0
