
		align	4
		label	L832_len__hla_ word
		dd	0eh
		dd	0eh
		label	L832_str__hla_ byte
		db	"Gimme iValue1:"
		db	0

		db	0

		align	4
		label	L854_len__hla_ word
		dd	0eh
		dd	0eh
		label	L854_str__hla_ byte
		db	"Gimme iValue2:"
		db	0

		db	0

		align	4
		label	L876_len__hla_ word
		dd	0eh
		dd	0eh
		label	L876_str__hla_ byte
		db	"Gimme iValue3:"
		db	0

		db	0

		align	4
		label	L898_len__hla_ word
		dd	017h
		dd	017h
		label	L898_str__hla_ byte
		db	"after noneZero iAnswer="
		db	0

