
		align	4
		label	L831_len__hla_ word
		dd	0eh
		dd	0eh
		label	L831_str__hla_ byte
		db	"Gimme iValue1:"
		db	0

		db	0

		align	4
		label	L853_len__hla_ word
		dd	0eh
		dd	0eh
		label	L853_str__hla_ byte
		db	"Gimme iValue2:"
		db	0

		db	0

		align	4
		label	L875_len__hla_ word
		dd	0eh
		dd	0eh
		label	L875_str__hla_ byte
		db	"Gimme iValue3:"
		db	0

		db	0

		align	4
		label	L897_len__hla_ word
		dd	013h
		dd	013h
		label	L897_str__hla_ byte
		db	"after makeSmallest!"
		db	0


		align	4
		label	L911_len__hla_ word
		dd	0ah
		dd	0ah
		label	L911_str__hla_ byte
		db	"iValue1 = "
		db	0

		db	0

		align	4
		label	L940_len__hla_ word
		dd	0ah
		dd	0ah
		label	L940_str__hla_ byte
		db	"iValue2 = "
		db	0

		db	0

		align	4
		label	L969_len__hla_ word
		dd	0ah
		dd	0ah
		label	L969_str__hla_ byte
		db	"iValue3 = "
		db	0

		db	0
